id = "oneway"
name = "Oneway"
version = "0.2.0"
schema_version = 1
authors = ["Oneway Contributors"]
description = "Oneway language support for Zed"

[grammars.oneway]
repository = "https://github.com/Almaju/oneway"
path = "editors/tree-sitter-oneway"
commit = "8bc3a3773b0d0f3baec79ef0e4a5ebc55887214b"
