use crate::parser::ast::*;
use std::collections::HashMap;
use std::fmt::Write;

/// Generate Rust source code from a Oneway AST module.
pub fn generate(module: &Module) -> String {
    let mut gen = RustCodegen::new();
    gen.emit_module(module);
    gen.output
}

struct RustCodegen {
    output: String,
    indent: usize,
    /// Track struct fields for auto-destructuring
    struct_fields: HashMap<String, Vec<String>>,
    /// Track newtypes for .value translation
    newtypes: HashMap<String, String>,
}

impl RustCodegen {
    fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            struct_fields: HashMap::new(),
            newtypes: HashMap::new(),
        }
    }

    // -----------------------------------------------------------------------
    // Indentation helpers
    // -----------------------------------------------------------------------

    fn indent_str(&self) -> String {
        "    ".repeat(self.indent)
    }

    fn write_indent(&mut self) {
        let indent = self.indent_str();
        self.output.push_str(&indent);
    }

    fn writeln(&mut self, s: &str) {
        self.write_indent();
        self.output.push_str(s);
        self.output.push('\n');
    }

    // -----------------------------------------------------------------------
    // Type mapping
    // -----------------------------------------------------------------------

    fn emit_type(type_expr: &TypeExpr) -> String {
        match type_expr {
            TypeExpr::Named(name) => Self::map_primitive_type(name),
            TypeExpr::Generic { name, params } => {
                let mapped_name = match name.as_str() {
                    "List" => "Vec".to_string(),
                    "Map" => "std::collections::HashMap".to_string(),
                    "Set" => "std::collections::HashSet".to_string(),
                    "Option" => "Option".to_string(),
                    "Result" => "Result".to_string(),
                    other => other.to_string(),
                };
                if name == "Result" && params.len() == 1 {
                    let t = Self::emit_type(&params[0]);
                    return format!("Result<{}, Box<dyn std::error::Error>>", t);
                }
                let param_strs: Vec<String> = params.iter().map(|p| Self::emit_type(p)).collect();
                format!("{}<{}>", mapped_name, param_strs.join(", "))
            }
            TypeExpr::Function {
                params,
                return_type,
            } => {
                let param_strs: Vec<String> = params.iter().map(|p| Self::emit_type(p)).collect();
                let ret = Self::emit_type(return_type);
                format!("fn({}) -> {}", param_strs.join(", "), ret)
            }
            TypeExpr::Union(types) => {
                let type_strs: Vec<String> = types.iter().map(|t| Self::emit_type(t)).collect();
                format!("/* {} */", type_strs.join(" | "))
            }
        }
    }

    fn map_primitive_type(name: &str) -> String {
        match name {
            "Int" => "i64".to_string(),
            "Float" => "f64".to_string(),
            "Bool" => "bool".to_string(),
            "String" => "String".to_string(),
            other => other.to_string(),
        }
    }

    // -----------------------------------------------------------------------
    // Variable name from type
    // -----------------------------------------------------------------------

    fn type_to_var_name(type_expr: &TypeExpr) -> String {
        let base = match type_expr {
            TypeExpr::Named(name) => name.clone(),
            TypeExpr::Generic { name, .. } => name.clone(),
            TypeExpr::Function { .. } => "func".to_string(),
            TypeExpr::Union(_) => "value".to_string(),
        };
        Self::lowercase_first_char(&base)
    }

    fn lowercase_first_char(s: &str) -> String {
        let mut chars = s.chars();
        match chars.next() {
            None => String::new(),
            Some(c) => {
                let lower: String = c.to_lowercase().collect();
                format!("{}{}", lower, chars.as_str())
            }
        }
    }

    // -----------------------------------------------------------------------
    // Module
    // -----------------------------------------------------------------------

    fn emit_module(&mut self, module: &Module) {
        // Preamble
        self.writeln("#![allow(non_snake_case, dead_code, unused_variables, unused_mut)]");
        self.writeln("// Generated by Oneway compiler");
        self.output.push('\n');
        self.writeln("use std::collections::HashMap;");
        self.writeln("use std::collections::HashSet;");
        self.output.push('\n');

        // First pass: collect struct fields and newtypes
        for item in &module.items {
            match item {
                Item::Struct(s) => {
                    let type_names: Vec<String> = s
                        .fields
                        .iter()
                        .map(|f| match &f.type_expr {
                            TypeExpr::Named(n) => n.clone(),
                            TypeExpr::Generic { name, .. } => name.clone(),
                            _ => "Unknown".to_string(),
                        })
                        .collect();
                    self.struct_fields.insert(s.name.clone(), type_names);
                }
                Item::Newtype(n) => {
                    let rust_type = Self::emit_type(&n.inner_type);
                    self.newtypes.insert(n.name.clone(), rust_type);
                }
                _ => {}
            }
        }

        // Second pass: emit code
        for item in &module.items {
            self.emit_item(item);
            self.output.push('\n');
        }
    }

    fn emit_item(&mut self, item: &Item) {
        match item {
            Item::Use(_) => {
                // Skip for now
            }
            Item::Struct(s) => self.emit_struct(s),
            Item::Enum(e) => self.emit_enum(e),
            Item::Contract(_) => {
                // Skip for now (compile-time concept)
            }
            Item::Function(f) => self.emit_function(f),
            Item::Newtype(n) => self.emit_newtype(n),
        }
    }

    // -----------------------------------------------------------------------
    // Newtype
    // -----------------------------------------------------------------------

    fn emit_newtype(&mut self, n: &NewtypeDef) {
        let rust_inner = Self::emit_type(&n.inner_type);
        self.writeln("#[derive(Debug, Clone, PartialEq)]");
        if n.public {
            self.write_indent();
            let _ = write!(self.output, "pub struct {} {{\n", n.name);
        } else {
            self.write_indent();
            let _ = write!(self.output, "struct {} {{\n", n.name);
        }
        self.indent += 1;
        self.write_indent();
        let _ = write!(self.output, "value: {},\n", rust_inner);
        self.indent -= 1;
        self.writeln("}");
    }

    // -----------------------------------------------------------------------
    // Struct
    // -----------------------------------------------------------------------

    fn emit_struct(&mut self, s: &StructDef) {
        self.writeln("#[derive(Debug, Clone)]");
        if s.public {
            self.write_indent();
            let _ = write!(self.output, "pub struct {} {{\n", s.name);
        } else {
            self.write_indent();
            let _ = write!(self.output, "struct {} {{\n", s.name);
        }
        self.indent += 1;
        for field in &s.fields {
            let type_name = match &field.type_expr {
                TypeExpr::Named(n) => n.clone(),
                TypeExpr::Generic { name, .. } => name.clone(),
                _ => "unknown".to_string(),
            };
            let field_name = Self::lowercase_first_char(&type_name);
            let rust_type = Self::emit_type(&field.type_expr);
            self.write_indent();
            let _ = write!(self.output, "{}: {},\n", field_name, rust_type);
        }
        self.indent -= 1;
        self.writeln("}");
    }

    // -----------------------------------------------------------------------
    // Enum
    // -----------------------------------------------------------------------

    fn emit_enum(&mut self, e: &EnumDef) {
        self.writeln("#[derive(Debug, Clone)]");
        if e.public {
            self.write_indent();
            let _ = write!(self.output, "pub enum {} {{\n", e.name);
        } else {
            self.write_indent();
            let _ = write!(self.output, "enum {} {{\n", e.name);
        }
        self.indent += 1;
        for variant in &e.variants {
            self.write_indent();
            match &variant.data {
                Some(data_type) => {
                    let rust_type = Self::emit_type(data_type);
                    let _ = write!(self.output, "{}({}),\n", variant.name, rust_type);
                }
                None => {
                    let _ = write!(self.output, "{},\n", variant.name);
                }
            }
        }
        self.indent -= 1;
        self.writeln("}");
    }

    // -----------------------------------------------------------------------
    // Function
    // -----------------------------------------------------------------------

    fn emit_function(&mut self, f: &FunctionDef) {
        // Build parameter list
        let mut param_strs = Vec::new();
        let mut var_names = Vec::new();

        for param in &f.params {
            let var_name = Self::type_to_var_name(&param.type_expr);
            let rust_type = Self::emit_type(&param.type_expr);
            param_strs.push(format!("{}: {}", var_name, rust_type));
            var_names.push(var_name);
        }

        let return_str = match &f.return_type {
            Some(t) => format!(" -> {}", Self::emit_type(t)),
            None => String::new(),
        };

        let pub_str = if f.public { "pub " } else { "" };
        self.write_indent();
        let _ = write!(
            self.output,
            "{}fn {}({}){} {{\n",
            pub_str,
            f.name,
            param_strs.join(", "),
            return_str
        );

        self.indent += 1;

        // Auto-destructure the first parameter if it's a known struct
        if !f.params.is_empty() {
            let first_type = &f.params[0].type_expr;
            if let TypeExpr::Named(type_name) = first_type {
                if let Some(field_type_names) = self.struct_fields.get(type_name).cloned() {
                    let var_name = &var_names[0];
                    let field_names: Vec<String> = field_type_names
                        .iter()
                        .map(|t| Self::lowercase_first_char(t))
                        .collect();
                    self.write_indent();
                    let _ = write!(
                        self.output,
                        "let {} {{ {} }} = {};\n",
                        type_name,
                        field_names.join(", "),
                        var_name
                    );
                }
            }
        }

        // Emit body
        self.emit_function_body(&f.body);

        self.indent -= 1;
        self.writeln("}");
    }

    fn emit_function_body(&mut self, body: &Expr) {
        match body {
            Expr::Block(exprs) => {
                let len = exprs.len();
                for (i, expr) in exprs.iter().enumerate() {
                    let is_last = i == len - 1;
                    self.emit_statement(expr, is_last);
                }
            }
            other => {
                // Single expression body
                self.emit_statement(other, true);
            }
        }
    }

    // -----------------------------------------------------------------------
    // Statements vs expressions
    // -----------------------------------------------------------------------

    fn emit_statement(&mut self, expr: &Expr, is_last: bool) {
        match expr {
            Expr::Binding { name, value } => {
                self.write_indent();
                let _ = write!(self.output, "let {} = ", name);
                self.emit_expr(value);
                self.output.push_str(";\n");
            }
            Expr::StructLiteral { type_name, fields } if !is_last => {
                // Auto-bind struct literals that are statements
                let var_name = Self::lowercase_first_char(type_name);
                self.write_indent();
                let _ = write!(self.output, "let {} = ", var_name);
                self.emit_struct_literal(type_name, fields);
                self.output.push_str(";\n");
            }
            _ => {
                self.write_indent();
                self.emit_expr(expr);
                if is_last {
                    self.output.push('\n');
                } else {
                    self.output.push_str(";\n");
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // Expression emission
    // -----------------------------------------------------------------------

    fn emit_expr(&mut self, expr: &Expr) {
        match expr {
            Expr::IntLiteral(n) => {
                let _ = write!(self.output, "{}", n);
            }
            Expr::FloatLiteral(f) => {
                if *f == (*f as i64) as f64 {
                    let _ = write!(self.output, "{:.1}", f);
                } else {
                    let _ = write!(self.output, "{}", f);
                }
            }
            Expr::StringLiteral(s) => {
                let _ = write!(self.output, "\"{}\".to_string()", Self::escape_string(s));
            }
            Expr::BoolLiteral(b) => {
                let _ = write!(self.output, "{}", b);
            }
            Expr::Identifier(name) => {
                self.output.push_str(name);
            }
            Expr::StringInterpolation(parts) => {
                self.emit_string_interpolation(parts);
            }
            Expr::BinaryOp { left, op, right } => {
                self.output.push('(');
                self.emit_expr(left);
                let op_str = match op {
                    BinOp::Add => " + ",
                    BinOp::Subtract => " - ",
                    BinOp::Multiply => " * ",
                    BinOp::Divide => " / ",
                    BinOp::Modulo => " % ",
                    BinOp::Equal => " == ",
                    BinOp::NotEqual => " != ",
                    BinOp::Less => " < ",
                    BinOp::Greater => " > ",
                    BinOp::LessEqual => " <= ",
                    BinOp::GreaterEqual => " >= ",
                    BinOp::And => " && ",
                    BinOp::Or => " || ",
                };
                self.output.push_str(op_str);
                self.emit_expr(right);
                self.output.push(')');
            }
            Expr::UnaryOp { op, operand } => {
                self.output.push('(');
                match op {
                    UnOp::Negate => self.output.push('-'),
                    UnOp::Not => self.output.push('!'),
                }
                self.emit_expr(operand);
                self.output.push(')');
            }
            Expr::DotAccess { object, field } => {
                self.emit_expr(object);
                let _ = write!(self.output, ".{}", field);
            }
            Expr::Call { function, argument } => {
                self.emit_call(function, argument);
            }
            Expr::StructLiteral { type_name, fields } => {
                self.emit_struct_literal(type_name, fields);
            }
            Expr::Match { subject, arms } => {
                self.emit_match(subject, arms);
            }
            Expr::Binding { name, value } => {
                let _ = write!(self.output, "let {} = ", name);
                self.emit_expr(value);
            }
            Expr::Block(exprs) => {
                self.emit_block(exprs);
            }
            Expr::Try(inner) => {
                self.emit_expr(inner);
                self.output.push('?');
            }
        }
    }

    // -----------------------------------------------------------------------
    // String interpolation
    // -----------------------------------------------------------------------

    fn emit_string_interpolation(&mut self, parts: &[StringPart]) {
        let mut fmt_string = String::new();
        let mut args: Vec<String> = Vec::new();

        for part in parts {
            match part {
                StringPart::Literal(s) => {
                    // Escape braces in the literal for format!
                    for ch in s.chars() {
                        match ch {
                            '{' => fmt_string.push_str("{{"),
                            '}' => fmt_string.push_str("}}"),
                            _ => fmt_string.push(ch),
                        }
                    }
                }
                StringPart::Expr(expr) => {
                    fmt_string.push_str("{}");
                    let mut arg_buf = RustCodegen::new();
                    // Copy state needed for emission
                    arg_buf.struct_fields = self.struct_fields.clone();
                    arg_buf.newtypes = self.newtypes.clone();
                    arg_buf.emit_expr(expr);
                    args.push(arg_buf.output);
                }
            }
        }

        if args.is_empty() {
            let _ = write!(self.output, "\"{}\".to_string()", fmt_string);
        } else {
            let _ = write!(
                self.output,
                "format!(\"{}\"{})",
                fmt_string,
                args.iter().map(|a| format!(", {}", a)).collect::<String>()
            );
        }
    }

    // -----------------------------------------------------------------------
    // Call
    // -----------------------------------------------------------------------

    fn emit_call(&mut self, function: &Expr, argument: &Option<Box<Expr>>) {
        match function {
            // UFCS call: object.method(arg?)
            Expr::DotAccess { object, field } => {
                if field == "print" {
                    self.output.push_str("println!(\"{:?}\", ");
                    self.emit_expr(object);
                    self.output.push(')');
                } else {
                    // Translate to free function call: method(object, arg?)
                    self.output.push_str(field);
                    self.output.push('(');
                    self.emit_expr(object);
                    if let Some(arg) = argument {
                        self.output.push_str(", ");
                        self.emit_expr(arg);
                    }
                    self.output.push(')');
                }
            }
            // Direct call: name(arg?)
            Expr::Identifier(name) => {
                if self.newtypes.contains_key(name) {
                    // Newtype constructor: Name { value: arg }
                    if let Some(arg) = argument {
                        let _ = write!(self.output, "{} {{ value: ", name);
                        self.emit_expr(arg);
                        self.output.push_str(" }");
                    } else {
                        // Newtype with no arg — unlikely but handle
                        let _ = write!(self.output, "{}()", name);
                    }
                } else {
                    self.output.push_str(name);
                    self.output.push('(');
                    if let Some(arg) = argument {
                        self.emit_expr(arg);
                    }
                    self.output.push(')');
                }
            }
            // Fallback: emit function expression then call
            other => {
                self.emit_expr(other);
                self.output.push('(');
                if let Some(arg) = argument {
                    self.emit_expr(arg);
                }
                self.output.push(')');
            }
        }
    }

    // -----------------------------------------------------------------------
    // Struct literal
    // -----------------------------------------------------------------------

    fn emit_struct_literal(&mut self, type_name: &str, fields: &[Expr]) {
        let _ = write!(self.output, "{} {{ ", type_name);
        if let Some(field_type_names) = self.struct_fields.get(type_name).cloned() {
            for (i, expr) in fields.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                if i < field_type_names.len() {
                    let field_name = Self::lowercase_first_char(&field_type_names[i]);
                    let _ = write!(self.output, "{}: ", field_name);
                }
                self.emit_field_value(expr);
            }
        } else {
            for (i, expr) in fields.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.emit_field_value(expr);
            }
        }
        self.output.push_str(" }");
    }

    fn emit_field_value(&mut self, expr: &Expr) {
        match expr {
            Expr::StringLiteral(s) => {
                let _ = write!(self.output, "\"{}\".to_string()", Self::escape_string(s));
            }
            _ => self.emit_expr(expr),
        }
    }

    // -----------------------------------------------------------------------
    // Match
    // -----------------------------------------------------------------------

    fn emit_match(&mut self, subject: &Option<Box<Expr>>, arms: &[MatchArm]) {
        match subject {
            Some(subj) => {
                self.output.push_str("match ");
                self.emit_expr(subj);
                self.output.push_str(" {\n");
                self.indent += 1;
                for arm in arms {
                    self.write_indent();
                    self.emit_pattern(&arm.pattern);
                    if let Some(guard) = &arm.guard {
                        self.output.push_str(" if ");
                        self.emit_expr(guard);
                    }
                    self.output.push_str(" => ");
                    self.emit_match_body(&arm.body);
                    self.output.push_str(",\n");
                }
                self.indent -= 1;
                self.write_indent();
                self.output.push('}');
            }
            None => {
                // Condition-based match: generate if/else chain
                self.emit_condition_match(arms);
            }
        }
    }

    fn emit_condition_match(&mut self, arms: &[MatchArm]) {
        for (i, arm) in arms.iter().enumerate() {
            if i == 0 {
                self.output.push_str("if ");
            } else if matches!(arm.pattern, Pattern::Wildcard) && arm.guard.is_none() {
                self.output.push_str(" else ");
            } else {
                self.output.push_str(" else if ");
            }

            // Emit the condition from guard if present
            let has_condition = if let Some(guard) = &arm.guard {
                self.emit_expr(guard);
                true
            } else if !matches!(arm.pattern, Pattern::Wildcard) {
                // The pattern itself might represent a condition
                // For now, emit a TODO
                self.output.push_str("true /* TODO: condition */");
                true
            } else {
                false
            };

            if has_condition {
                self.output.push_str(" {\n");
            } else {
                self.output.push_str("{\n");
            }

            self.indent += 1;
            self.write_indent();
            self.emit_expr(&arm.body);
            self.output.push('\n');
            self.indent -= 1;
            self.write_indent();
            self.output.push('}');
        }
    }

    fn emit_match_body(&mut self, body: &Expr) {
        match body {
            Expr::Block(exprs) => {
                self.output.push_str("{\n");
                self.indent += 1;
                let len = exprs.len();
                for (i, expr) in exprs.iter().enumerate() {
                    let is_last = i == len - 1;
                    self.emit_statement(expr, is_last);
                }
                self.indent -= 1;
                self.write_indent();
                self.output.push('}');
            }
            _ => {
                self.emit_expr(body);
            }
        }
    }

    fn emit_pattern(&mut self, pattern: &Pattern) {
        match pattern {
            Pattern::Wildcard => {
                self.output.push('_');
            }
            Pattern::Literal(expr) => {
                self.emit_expr(expr);
            }
            Pattern::Binding(name) => {
                self.output.push_str(name);
            }
            Pattern::Struct { type_name, fields } => {
                let _ = write!(self.output, "{} {{ ", type_name);
                for (i, pattern) in fields.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.emit_pattern(pattern);
                }
                self.output.push_str(" }");
            }
            Pattern::EnumVariant {
                type_name,
                variant,
                data,
            } => {
                if let Some(tn) = type_name {
                    let _ = write!(self.output, "{}::{}", tn, variant);
                } else {
                    self.output.push_str(variant);
                }
                if let Some(data_pat) = data {
                    self.output.push('(');
                    self.emit_pattern(data_pat);
                    self.output.push(')');
                }
            }
        }
    }

    // -----------------------------------------------------------------------
    // Block
    // -----------------------------------------------------------------------

    fn emit_block(&mut self, exprs: &[Expr]) {
        self.output.push_str("{\n");
        self.indent += 1;
        let len = exprs.len();
        for (i, expr) in exprs.iter().enumerate() {
            let is_last = i == len - 1;
            self.emit_statement(expr, is_last);
        }
        self.indent -= 1;
        self.write_indent();
        self.output.push('}');
    }

    // -----------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------

    fn escape_string(s: &str) -> String {
        s.replace('\\', "\\\\")
            .replace('"', "\\\"")
            .replace('\n', "\\n")
            .replace('\r', "\\r")
            .replace('\t', "\\t")
    }
}

// ===========================================================================
// Tests
// ===========================================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::Span;

    fn s() -> Span {
        Span::default()
    }

    #[test]
    fn generate_newtype() {
        let module = Module {
            items: vec![Item::Newtype(NewtypeDef {
                public: false,
                name: "TaskId".into(),
                inner_type: TypeExpr::Named("Int".into()),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("struct TaskId"));
        assert!(output.contains("value: i64"));
    }

    #[test]
    fn generate_struct() {
        let module = Module {
            items: vec![Item::Struct(StructDef {
                public: false,
                name: "Person".into(),
                fields: vec![
                    Field {
                        type_expr: TypeExpr::Named("Int".into()),
                        span: s(),
                    },
                    Field {
                        type_expr: TypeExpr::Named("String".into()),
                        span: s(),
                    },
                ],
                delegates: vec![],
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("struct Person"));
        assert!(output.contains("int: i64"), "output was: {}", output);
        assert!(output.contains("string: String"), "output was: {}", output);
    }

    #[test]
    fn generate_function_with_destructuring() {
        let module = Module {
            items: vec![
                Item::Struct(StructDef {
                    public: false,
                    name: "Point".into(),
                    fields: vec![
                        Field {
                            type_expr: TypeExpr::Named("X".into()),
                            span: s(),
                        },
                        Field {
                            type_expr: TypeExpr::Named("Y".into()),
                            span: s(),
                        },
                    ],
                    delegates: vec![],
                    span: s(),
                }),
                Item::Function(FunctionDef {
                    public: false,
                    name: "sum".into(),
                    params: vec![Param {
                        type_expr: TypeExpr::Named("Point".into()),
                        span: s(),
                    }],
                    return_type: Some(TypeExpr::Named("Int".into())),
                    body: Expr::Block(vec![Expr::BinaryOp {
                        left: Box::new(Expr::Identifier("x".into())),
                        op: BinOp::Add,
                        right: Box::new(Expr::Identifier("y".into())),
                    }]),
                    span: s(),
                }),
            ],
        };
        let output = generate(&module);
        assert!(output.contains("fn sum(point: Point) -> i64"));
        assert!(
            output.contains("let Point { x, y } = point;"),
            "output was: {}",
            output
        );
    }

    #[test]
    fn generate_enum() {
        let module = Module {
            items: vec![Item::Enum(EnumDef {
                public: false,
                name: "Color".into(),
                variants: vec![
                    Variant {
                        name: "Blue".into(),
                        data: None,
                        span: s(),
                    },
                    Variant {
                        name: "Red".into(),
                        data: None,
                        span: s(),
                    },
                ],
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("enum Color"));
        assert!(output.contains("Blue"));
        assert!(output.contains("Red"));
    }

    #[test]
    fn generate_enum_with_data() {
        let module = Module {
            items: vec![Item::Enum(EnumDef {
                public: false,
                name: "Shape".into(),
                variants: vec![
                    Variant {
                        name: "Circle".into(),
                        data: Some(TypeExpr::Named("Float".into())),
                        span: s(),
                    },
                    Variant {
                        name: "Square".into(),
                        data: Some(TypeExpr::Named("Float".into())),
                        span: s(),
                    },
                ],
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("Circle(f64)"));
        assert!(output.contains("Square(f64)"));
    }

    #[test]
    fn generate_string_interpolation() {
        let module = Module {
            items: vec![Item::Function(FunctionDef {
                public: false,
                name: "greet".into(),
                params: vec![],
                return_type: Some(TypeExpr::Named("String".into())),
                body: Expr::Block(vec![Expr::StringInterpolation(vec![
                    StringPart::Literal("Hello, ".into()),
                    StringPart::Expr(Box::new(Expr::Identifier("name".into()))),
                    StringPart::Literal("!".into()),
                ])]),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("format!(\"Hello, {}!\""));
        assert!(output.contains("name"));
    }

    #[test]
    fn generate_match_expr() {
        let module = Module {
            items: vec![Item::Function(FunctionDef {
                public: false,
                name: "describe".into(),
                params: vec![Param {
                    type_expr: TypeExpr::Named("Int".into()),
                    span: s(),
                }],
                return_type: Some(TypeExpr::Named("String".into())),
                body: Expr::Block(vec![Expr::Match {
                    subject: Some(Box::new(Expr::Identifier("int".into()))),
                    arms: vec![
                        MatchArm {
                            pattern: Pattern::Literal(Box::new(Expr::IntLiteral(0))),
                            guard: None,
                            body: Expr::StringLiteral("zero".into()),
                        },
                        MatchArm {
                            pattern: Pattern::Wildcard,
                            guard: None,
                            body: Expr::StringLiteral("other".into()),
                        },
                    ],
                }]),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("match int"));
        assert!(output.contains("0 =>"));
        assert!(output.contains("_ =>"));
    }

    #[test]
    fn generate_newtype_constructor() {
        let module = Module {
            items: vec![
                Item::Newtype(NewtypeDef {
                    public: false,
                    name: "TaskId".into(),
                    inner_type: TypeExpr::Named("Int".into()),
                    span: s(),
                }),
                Item::Function(FunctionDef {
                    public: false,
                    name: "make".into(),
                    params: vec![],
                    return_type: Some(TypeExpr::Named("TaskId".into())),
                    body: Expr::Block(vec![Expr::Call {
                        function: Box::new(Expr::Identifier("TaskId".into())),
                        argument: Some(Box::new(Expr::IntLiteral(42))),
                    }]),
                    span: s(),
                }),
            ],
        };
        let output = generate(&module);
        assert!(output.contains("TaskId { value: 42 }"));
    }

    #[test]
    fn generate_print_call() {
        let module = Module {
            items: vec![Item::Function(FunctionDef {
                public: false,
                name: "main".into(),
                params: vec![],
                return_type: None,
                body: Expr::Block(vec![Expr::Call {
                    function: Box::new(Expr::DotAccess {
                        object: Box::new(Expr::IntLiteral(42)),
                        field: "print".into(),
                    }),
                    argument: None,
                }]),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("println!(\"{:?}\", 42)"));
    }

    #[test]
    fn generate_ufcs_call() {
        let module = Module {
            items: vec![Item::Function(FunctionDef {
                public: false,
                name: "main".into(),
                params: vec![],
                return_type: None,
                body: Expr::Block(vec![Expr::Call {
                    function: Box::new(Expr::DotAccess {
                        object: Box::new(Expr::Identifier("x".into())),
                        field: "double".into(),
                    }),
                    argument: None,
                }]),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("double(x)"));
    }

    #[test]
    fn generate_try_expr() {
        let module = Module {
            items: vec![Item::Function(FunctionDef {
                public: false,
                name: "read".into(),
                params: vec![],
                return_type: None,
                body: Expr::Block(vec![Expr::Try(Box::new(Expr::Call {
                    function: Box::new(Expr::Identifier("open".into())),
                    argument: Some(Box::new(Expr::StringLiteral("file.txt".into()))),
                }))]),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("open(\"file.txt\".to_string())?"));
    }

    #[test]
    fn generate_binding() {
        let module = Module {
            items: vec![Item::Function(FunctionDef {
                public: false,
                name: "main".into(),
                params: vec![],
                return_type: None,
                body: Expr::Block(vec![
                    Expr::Binding {
                        name: "x".into(),
                        value: Box::new(Expr::IntLiteral(10)),
                    },
                    Expr::Identifier("x".into()),
                ]),
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("let x = 10;"));
    }

    #[test]
    fn generate_public_struct() {
        let module = Module {
            items: vec![Item::Struct(StructDef {
                public: true,
                name: "Pos".into(),
                fields: vec![Field {
                    type_expr: TypeExpr::Named("Int".into()),
                    span: s(),
                }],
                delegates: vec![],
                span: s(),
            })],
        };
        let output = generate(&module);
        assert!(output.contains("pub struct Pos"));
    }

    #[test]
    fn type_mapping_primitives() {
        assert_eq!(
            RustCodegen::emit_type(&TypeExpr::Named("Int".into())),
            "i64"
        );
        assert_eq!(
            RustCodegen::emit_type(&TypeExpr::Named("Float".into())),
            "f64"
        );
        assert_eq!(
            RustCodegen::emit_type(&TypeExpr::Named("Bool".into())),
            "bool"
        );
        assert_eq!(
            RustCodegen::emit_type(&TypeExpr::Named("String".into())),
            "String"
        );
    }

    #[test]
    fn type_mapping_generics() {
        let list_int = TypeExpr::Generic {
            name: "List".into(),
            params: vec![TypeExpr::Named("Int".into())],
        };
        assert_eq!(RustCodegen::emit_type(&list_int), "Vec<i64>");

        let map_str_int = TypeExpr::Generic {
            name: "Map".into(),
            params: vec![
                TypeExpr::Named("String".into()),
                TypeExpr::Named("Int".into()),
            ],
        };
        assert_eq!(
            RustCodegen::emit_type(&map_str_int),
            "std::collections::HashMap<String, i64>"
        );
    }

    #[test]
    fn type_mapping_result_single_param() {
        let result_int = TypeExpr::Generic {
            name: "Result".into(),
            params: vec![TypeExpr::Named("Int".into())],
        };
        assert_eq!(
            RustCodegen::emit_type(&result_int),
            "Result<i64, Box<dyn std::error::Error>>"
        );
    }

    #[test]
    fn type_to_var_name_cases() {
        assert_eq!(
            RustCodegen::type_to_var_name(&TypeExpr::Named("Greeting".into())),
            "greeting"
        );
        assert_eq!(
            RustCodegen::type_to_var_name(&TypeExpr::Named("HttpClient".into())),
            "httpClient"
        );
        assert_eq!(
            RustCodegen::type_to_var_name(&TypeExpr::Named("Int".into())),
            "int"
        );
        assert_eq!(
            RustCodegen::type_to_var_name(&TypeExpr::Generic {
                name: "List".into(),
                params: vec![TypeExpr::Named("Int".into())],
            }),
            "list"
        );
    }

    #[test]
    fn generate_two_param_function() {
        let module = Module {
            items: vec![
                Item::Struct(StructDef {
                    public: false,
                    name: "Wallet".into(),
                    fields: vec![
                        Field {
                            type_expr: TypeExpr::Named("Balance".into()),
                            span: s(),
                        },
                        Field {
                            type_expr: TypeExpr::Named("Name".into()),
                            span: s(),
                        },
                    ],
                    delegates: vec![],
                    span: s(),
                }),
                Item::Function(FunctionDef {
                    public: false,
                    name: "addBalance".into(),
                    params: vec![
                        Param {
                            type_expr: TypeExpr::Named("Wallet".into()),
                            span: s(),
                        },
                        Param {
                            type_expr: TypeExpr::Named("Int".into()),
                            span: s(),
                        },
                    ],
                    return_type: Some(TypeExpr::Named("Wallet".into())),
                    body: Expr::Block(vec![Expr::Identifier("wallet".into())]),
                    span: s(),
                }),
            ],
        };
        let output = generate(&module);
        assert!(output.contains("fn addBalance(wallet: Wallet, int: i64) -> Wallet"));
        assert!(
            output.contains("let Wallet { balance, name } = wallet;"),
            "output was: {}",
            output
        );
    }

    #[test]
    fn preamble_present() {
        let module = Module { items: vec![] };
        let output = generate(&module);
        assert!(output.contains("#![allow(non_snake_case"));
        assert!(output.contains("// Generated by Oneway compiler"));
        assert!(output.contains("use std::collections::HashMap;"));
        assert!(output.contains("use std::collections::HashSet;"));
    }
}
