name = "Oneway"
grammar = "oneway"
path_suffixes = ["ow"]
language_servers = ["oneway-lsp"]
line_comments = []
autoclose_before = ";:.,=}])> \n\t"
brackets = [
  { start = "{", end = "}", close = true, newline = true, indent = true },
  { start = "(", end = ")", close = true, newline = false },
  { start = "<", end = ">", close = false, newline = false },
]
word_characters = ["_"]
